-- Adds Arabic names/descriptions for all 85 menu items (and Mojito's 5
-- flavor variants). Run this once in the Supabase SQL editor, after the
-- category and section migrations.

alter table items add column if not exists name_ar text;
alter table items add column if not exists description_ar text;
alter table variants add column if not exists name_ar text;

update items set name_ar = 'إسبريسو', description_ar = 'جرعة مزدوجة' where name = 'Espresso';
update items set name_ar = 'أمريكانو', description_ar = 'ساخن أو مثلج' where name = 'Americano';
update items set name_ar = 'كورتادو', description_ar = '80 مل، أجزاء متساوية من الإسبريسو والحليب' where name = 'Cortado';
update items set name_ar = 'كابتشينو' where name = 'Cappuccino';
update items set name_ar = 'فلات وايت' where name = 'Flat White';
update items set name_ar = 'أفوجاتو' where name = 'Affogato';
update items set name_ar = 'لاتيه القهوة' where name = 'Coffee Latte';
update items set name_ar = 'موكا' where name = 'Mocha';
update items set name_ar = 'لاتيه إسباني', description_ar = 'حليب مكثف، حلو وغني' where name = 'Spanish Latte';
update items set name_ar = 'لاتيه كراميل مملح' where name = 'Salted Caramel Latte';
update items set name_ar = 'لاتيه رول القرفة' where name = 'Cinnamon Roll Latte';
update items set name_ar = 'لاتيه تشيز كيك' where name = 'Cheesecake Latte';
update items set name_ar = 'لاتيه البندق' where name = 'Hazelnut Latte';
update items set name_ar = 'لاتيه الزعفران' where name = 'Saffron Latte';
update items set name_ar = 'لاتيه التمر', description_ar = 'تمر محلي مخفوق' where name = 'Date Latte';
update items set name_ar = 'لاتيه تيراميسو' where name = 'Tiramisu Latte';
update items set name_ar = 'V60 كلاسيك' where name = 'Classic V60';
update items set name_ar = 'V60 مميز', description_ar = 'كولومبي، درجة مختصة 85+' where name = 'Premium V60';
update items set name_ar = 'كولد برو مميز' where name = 'Signature Cold Brew';
update items set name_ar = 'كولد برو الليمون الذهبي' where name = 'Golden Lime Cold Brew';
update items set name_ar = 'كولد برو', description_ar = '250 مل، حبوب إثيوبية مختصة' where name = 'Cold Brew';
update items set name_ar = 'شاي أسود / أخضر' where name = 'Black / Green Tea';
update items set name_ar = 'ليمون غراس بالزنجبيل' where name = 'Lemongrass Ginger';
update items set name_ar = 'كوين بيري', description_ar = 'كركديه، فراولة، توت بري، بربري' where name = 'Queen Berry';
update items set name_ar = 'ياسمين ملكي', description_ar = 'شاي أخضر وأزهار الياسمين' where name = 'Royal Jasmine';
update items set name_ar = 'إنجليش بريكفاست' where name = 'English Breakfast';
update items set name_ar = 'إيرل غراي', description_ar = 'شاي أسود بنكهة البرغموت' where name = 'Earl Grey';
update items set name_ar = 'نعناع مغربي' where name = 'Moroccan Mint';
update items set name_ar = 'حلم الكراميل' where name = 'Caramel Dream';
update items set name_ar = 'إنديان سمر' where name = 'Indian Summer';
update items set name_ar = 'شاي مثلج بالخوخ' where name = 'Peach Ice Tea';
update items set name_ar = 'شاي مثلج بالمانجا وفاكهة الشغف' where name = 'Mango Passion Ice Tea';
update items set name_ar = 'شاي مثلج بالتوت المشكل' where name = 'MixBerry Ice Tea';
update items set name_ar = 'شاي مثلج بالأناناس' where name = 'Pineapple Ice Tea';
update items set name_ar = 'شاي مثلج بالرمان وجوز الهند' where name = 'Pomegranate Coconut Ice Tea';
update items set name_ar = 'لاتيه ماتشا' where name = 'Matcha Latte';
update items set name_ar = 'ماتشا إسباني', description_ar = 'حليب مكثف' where name = 'Spanish Matcha';
update items set name_ar = 'فراولة كريمية' where name = 'Creamy Strawberry';
update items set name_ar = 'مانجا كريمية' where name = 'Creamy Mango';
update items set name_ar = 'خوخ كريمي' where name = 'Creamy Peach';
update items set name_ar = 'أناناس كريمي' where name = 'Creamy Pineapple';
update items set name_ar = 'فاكهة الشغف' where name = 'Passion Fruit';
update items set name_ar = 'فستق' where name = 'Pistachio';
update items set name_ar = 'موكا بيضاء' where name = 'White Mocha';
update items set name_ar = 'ميلك شيك ماتشا' where name = 'Matcha Milkshake';
update items set name_ar = 'كوكو باين', description_ar = 'أناناس وجوز الهند، مثلج' where name = 'Coco Pine';
update items set name_ar = 'كركديه', description_ar = 'كركديه مميز بالزنجبيل والورد' where name = 'Hibiscus';
update items set name_ar = 'موهيتو' where name = 'Mojito';
update items set name_ar = 'بينا كولادا', description_ar = 'مزيج مميز من الأناناس وجوز الهند' where name = 'Piña Colada';
update items set name_ar = 'بلاك ماجيك', description_ar = 'فوار، بقاعدة الفراولة' where name = 'Black Magic';
update items set name_ar = 'باشن إسبريسو', description_ar = 'فوار، فاكهة الشغف والإسبريسو' where name = 'Passionpresso';
update items set name_ar = 'موهيتو ريدبُل', description_ar = 'موهيتو مع جرعة طاقة' where name = 'Redbull Mojito';
update items set name_ar = 'توت مشكل' where name = 'Mixed Berry';
update items set name_ar = 'لوتس' where name = 'Lotus';
update items set name_ar = 'أوريو' where name = 'Oreo';
update items set name_ar = 'كراميل' where name = 'Caramel';
update items set name_ar = 'نوتيلا' where name = 'Nutella';
update items set name_ar = 'زبدة الفول السوداني والموز' where name = 'Peanut Butter & Banana';
update items set name_ar = 'سادة' where name = 'Plain';
update items set name_ar = 'شوكولاتة' where name = 'Chocolate';
update items set name_ar = 'نوتيلا وفراولة' where name = 'Nutella Strawberry';
update items set name_ar = 'زبدة الفول السوداني والموز' where name = 'Peanut Butter Banana';
update items set name_ar = 'مرتديلا', description_ar = 'خس، جبنة تشيدر، طماطم، خيار، فطر' where name = 'Mortadella';
update items set name_ar = 'حلوم مشوي' where name = 'Grilled Halloumi';
update items set name_ar = 'ديك رومي مدخن', description_ar = 'صدر ديك رومي مدخن، خس، جبنة تشيدر، طماطم، خيار، فطر' where name = 'Smoked Turkey';
update items set name_ar = 'جبنة وزعتر' where name = 'Cheese Za''atar';
update items set name_ar = 'تشيز كيك فاكهة الشغف' where name = 'Passionfruit Cheesecake';
update items set name_ar = 'تشيز كيك التوت المشكل' where name = 'Mixed Berry Cheesecake';
update items set name_ar = 'تشيز كيك الفستق' where name = 'Pistachio Cheese Cake';
update items set name_ar = 'تيراميسو' where name = 'Tiramisu';
update items set name_ar = 'سان سيباستيان', description_ar = 'تشيز كيك باسك المحروق' where name = 'San Sebastián';
update items set name_ar = 'براوني', description_ar = 'يُقدَّم ساخنًا مع كرة آيس كريم الفانيليا' where name = 'Brownie';
update items set name_ar = 'براوني مرمر', description_ar = 'يُقدَّم ساخنًا مع كرة آيس كريم الفانيليا' where name = 'Marble Brownie';
update items set name_ar = 'سموذي أساي', description_ar = 'هريس أساي عضوي، فراولة، توت أزرق، موز، زبدة الفول السوداني، ماء جوز الهند وعسل' where name = 'Açaí Smoothie';
update items set name_ar = 'بول أساي', description_ar = 'هريس أساي عضوي، فراولة، توت أزرق، موز، غرانولا، زبدة الفول السوداني، بذور شيا وعسل' where name = 'Açaí Bowl';
update items set name_ar = 'برو ماغ كيك' where name = 'Pro Mug Cake';
update items set name_ar = 'باور براوني' where name = 'Power Brownie';
update items set name_ar = 'رايس كيك بالجبنة والطماطم' where name = 'Cheese and Tomato Rice Cake';
update items set name_ar = 'رايس كيك بزبدة الفول السوداني والفراولة' where name = 'Peanut Butter Strawberry Rice Cake';
update items set name_ar = 'رايس كيك تيراميسو', description_ar = 'رايس كيك منقوع بالإسبريسو، زبادي يوناني، بروتين واي، مسحوق الكاكاو' where name = 'Tiramisu Rice Cake';
update items set name_ar = 'سلطة تونة', description_ar = 'تونة، خس، طماطم كرزية، خيار، ذرة، زيت زيتون، ملح وفلفل' where name = 'Tuna Salad';
update items set name_ar = 'فيت لاتيه', description_ar = 'لاتيه القهوة + بروتين واي' where name = 'Fit Latte';
update items set name_ar = 'بَلك فيول', description_ar = 'بروتين واي، موز، تمر، مسحوق الكاكاو' where name = 'Bulk Fuel';
update items set name_ar = 'شاي مثلج بالمانجا وفاكهة الشغف', description_ar = 'خالٍ من السكر' where name = 'Mango Passion Ice tea';

-- Mojito flavor variants
update variants set name_ar = 'كلاسيك' where name = 'Classic';
update variants set name_ar = 'أناناس' where name = 'Pineapple';
update variants set name_ar = 'خوخ' where name = 'Peach';
update variants set name_ar = 'مانجا' where name = 'Mango';
update variants set name_ar = 'فاكهة الشغف' where name = 'Passion Fruit';
